### ISSUE TITLE
tie in to stolen-party speed/rotate/move stuff

### ISSUE THREAD

**Issue by tylerrasor** [tylerrasor/party-party-partyinator#4]
since the original party-party-party code allows for speed control, rotation, and movement, it would be nice to expose those things to the user

I feel like some kind of control strip (or control**s** strip, as it were) could either replace the uploadinator or appear between the party space and the download/reset buttons

**Comment by cah-tylerrasor** [comment]
![image](https://user-images.githubusercontent.com/37845333/84807156-d0d88600-afd4-11ea-9a9f-b3f926588577.png)
![image](https://user-images.githubusercontent.com/37845333/84807168-d59d3a00-afd4-11ea-95eb-ca8f8b786859.png)

it's not pretty, but there's a thing to hold controls now
